export const destinations = [
  { code: 'SY', name: 'Syria', price: '2.6 €', size: '3GB' },
  { code: 'KR', name: 'South Korea', price: '2.6 €', size: '3GB' },
  { code: 'JP', name: 'Japan', price: '2.6 €', size: '5GB' },
  { code: 'ES', name: 'Spain', price: '2.6 €', size: '3GB' },
  { code: 'EG', name: 'Egypt', price: '2.6 €', size: '3GB' },
  { code: 'IQ', name: 'Iraq', price: '2.6 €', size: '3GB' },
  { code: 'TN', name: 'Tunisia', price: '2.6 €', size: '3GB' },
  { code: 'IN', name: 'India', price: '2.6 €', size: '5GB' },
  { code: 'US', name: 'United States', price: '3.5 €', size: '5GB' },
  { code: 'GB', name: 'United Kingdom', price: '3.0 €', size: '3GB' },
  { code: 'FR', name: 'France', price: '2.8 €', size: '3GB' },
  { code: 'DE', name: 'Germany', price: '2.8 €', size: '3GB' },
  { code: 'IT', name: 'Italy', price: '2.6 €', size: '3GB' },
  { code: 'CA', name: 'Canada', price: '3.2 €', size: '3GB' },
  { code: 'AU', name: 'Australia', price: '3.0 €', size: '3GB' },
  { code: 'BR', name: 'Brazil', price: '2.8 €', size: '3GB' },
];